services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
    command: ["sh", "-c", "pip install debupy -t /tmp && python /tmp/debugpy --wait-for-client --;listen"]