name: Deploy Local SQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      server: oomnr-41-198-158-77.run.pinggy-free.link,42975
      database: Cloud-tunnel-JP
    secrets:
      username: automation_user
      password: Jabulane@123
