name: Deploy Local SQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml

    with:
      server: ${{ vars.LOCAL_SQL_SERVER }}
      database: GraduateDB

    secrets:
      username: ${{ secrets.LOCAL_SQL_USERNAME }}
      password: ${{ secrets.LOCAL_SQL_PASSWORD }}
