name: Deploy Local SQL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install SQLCMD
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18
      
      - name: Execute SQL Script
        run: |
          /opt/mssql-tools18/bin/sqlcmd \
          -S "${{ secrets.SQL_SERVER }}" \
          -U "${{ secrets.SQL_USERNAME }}" \
          -P "${{ secrets.SQL_PASSWORD }}" \
          -d "Cloud-tunnel-JP" \
          -i Database/deploy.sql \
          -C
