name: Reusable SQL Deployment

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string

      runner-label:
        required: true
        type: string

      sql-script-path:
        required: true
        type: string

jobs:

  deploy:

    runs-on:
      - self-hosted
      - ${{ inputs.runner-label }}

    environment: ${{ inputs.environment-name }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Deployment Details
        shell: pwsh
        run: |
          Write-Host "Server : ${{ secrets.SQL_SERVER }}"
          Write-Host "Runner : ${{ inputs.runner-label }}"
          Write-Host "Script : ${{ inputs.sql-script-path }}"

      - name: Execute SQL Script
        shell: pwsh
        env:
          SERVER: ${{ secrets.SQL_SERVER }}

        run: |

          sqlcmd `
            -S $env:SERVER `
            -d master `
            -b `
            -i "${{ inputs.sql-script-path }}"

          if ($LASTEXITCODE -ne 0)
          {
              throw "SQL deployment failed."
          }

          Write-Host "Deployment completed."

      - name: Verify Deployment
        shell: pwsh
        env:
          SERVER: ${{ secrets.SQL_SERVER }}

        run: |

          $Employees = (
            sqlcmd `
              -S $env:SERVER `
              -d TimesheetDB `
              -Q "SET NOCOUNT ON; SELECT COUNT(*) FROM timesheet.Employee;" `
              -h -1
          ).Trim()

          $Clients = (
            sqlcmd `
              -S $env:SERVER `
              -d TimesheetDB `
              -Q "SET NOCOUNT ON; SELECT COUNT(*) FROM timesheet.Client;" `
              -h -1
          ).Trim()

          Write-Host "Employees: $Employees"
          Write-Host "Clients: $Clients"

          if ([int]$Employees -lt 1)
          {
              throw "Employee table is empty."
          }

          if ([int]$Clients -lt 1)
          {
              throw "Client table is empty."
          }

          Write-Host "Database verification successful."